### ISSUE TITLE
Broken types for `exclamationToken` hooks

### ISSUE THREAD

**Issue by Xiot** [wessberg/ts-clone-node#14] opened 2023-08-06 02:17 UTC
First of all a huge thank you for this project!

I noticed that the typing for the hooks seems to be a little wonky.

This is reporting errors
```typescript
hook: node => {
  return {
    exclamationToken: cur => ts.factory.createToken(ts.SyntaxKind.ExclamationToken)
  }
}
```

However if I add in `modifiers` it works.
```typescript
hook: node => {
  return {
    modifiers => cur => undefined,
    exclamationToken: cur => ts.factory.createToken(ts.SyntaxKind.ExclamationToken)
  }
}
```

Looking at the type for the hook,
```typescript
type CloneNodeHookFactory<T extends MetaNode> = (node: T, payload: CloneNodeHookFactoryPayload) => CloneNodeHook<T> | undefined;
```

It looks like its because `exclamationToken` isn't defined in `MetaNode`.  It works once I added `modifiers` since the type now extends `MetaNode`

**Comment by wessberg** [comment] 2023-08-06 19:33
Huh, that's weird. It shouldn't have to declare a hook for `modifiers` to extend `MetaNode`, as the `modifiers` property on `MetaNode` is optional.

Which TypeScript version are you using, and can you provide me with a little more info so that I can reproduce it?

With TS 5.1, I just hacked the following together, and it typechecks correctly:

```ts
import {VariableDeclaration} from "typescript";

cloneNode({} as VariableDeclaration, {
	hook: () => ({
		exclamationToken: current => current
	})
  })
```

**Comment by wessberg** [comment] 2024-09-24 21:36
I'm closing this issue, since I never heard back from you :)

**Closed as completed by wessberg** 2024-09-24 21:36 UTC
